import { defineConfig } from "vitepress";

export default defineConfig({
  lang: "ja",
  title: "sharin",
  description: "車輪の再発明で学び直す教科書",
  themeConfig: {
    nav: [{ text: "教科書", link: "/parts/rate-limiter" }],
    sidebar: [
      {
        text: "トラフィック制御と観測",
        items: [
          { text: "Rate Limiter", link: "/parts/rate-limiter" },
          { text: "サーキットブレーカー", link: "/parts/circuit-breaker" },
          { text: "リトライとバックオフ", link: "/parts/retry-backoff" },
          { text: "ロードバランサ", link: "/parts/load-balancer" },
          { text: "メトリクスとヒストグラム", link: "/parts/metrics" },
          { text: "時系列の整列と集約", link: "/parts/timeseries" },
          { text: "分散トレーシング", link: "/parts/tracing" },
          { text: "Trace Sampling", link: "/parts/trace-sampling" },
        ],
      },
      {
        text: "ネットワーク下層",
        items: [
          { text: "TCP/IP", link: "/parts/tcp" },
          { text: "HTTPサーバ", link: "/parts/http-server" },
          { text: "HTTP/2 多重化", link: "/parts/http2" },
          { text: "WebSocket", link: "/parts/websocket" },
          { text: "輻輳制御(AIMD)", link: "/parts/congestion" },
          { text: "DNSリゾルバ", link: "/parts/dns" },
          { text: "プロキシ", link: "/parts/proxy" },
        ],
      },
      {
        text: "データの持ち方",
        items: [
          { text: "ID Generation", link: "/parts/id-generation" },
          { text: "二分探索木", link: "/parts/binary-search-tree" },
          { text: "LRUキャッシュ", link: "/parts/lru-cache" },
          { text: "ディスクとページ", link: "/parts/disk-and-pages" },
          { text: "B-Tree", link: "/parts/btree" },
          { text: "ログ構造KV", link: "/parts/log-structured-kv" },
          { text: "WAL", link: "/parts/wal" },
          { text: "バッファプール", link: "/parts/buffer-pool" },
          { text: "B-Treeページストア", link: "/parts/btree-page-store" },
          { text: "B-Tree + WAL", link: "/parts/btree-wal" },
          { text: "ミニSQL", link: "/parts/mini-sql" },
          { text: "セカンダリインデックス", link: "/parts/secondary-index" },
          { text: "MVCC / 分離レベル", link: "/parts/mvcc" },
          { text: "ハッシュマップ", link: "/parts/hash-map" },
          { text: "ブルームフィルタ", link: "/parts/bloom-filter" },
          { text: "スキップリスト", link: "/parts/skip-list" },
          { text: "転置インデックス", link: "/parts/inverted-index" },
        ],
      },
      {
        text: "分散システム",
        items: [
          { text: "分散はなぜ難しいか", link: "/parts/distributed-intro" },
          { text: "論理時計とベクタークロック", link: "/parts/logical-clock" },
          { text: "因果順序の配送", link: "/parts/causal-broadcast" },
          { text: "全順序放送", link: "/parts/total-order" },
          { text: "Raft — 分散合意", link: "/parts/raft" },
          { text: "レプリケーション", link: "/parts/replication" },
          { text: "CRDT", link: "/parts/crdt" },
          { text: "コンシステントハッシュ", link: "/parts/consistent-hashing" },
          { text: "クォーラム", link: "/parts/quorum" },
          { text: "差分の突き合わせ", link: "/parts/anti-entropy" },
          { text: "ゴシップと障害検知", link: "/parts/gossip" },
          { text: "分散ロック", link: "/parts/distributed-lock" },
          { text: "分散トランザクション", link: "/parts/distributed-txn" },
          { text: "キャパシティ見積もり", link: "/parts/capacity-estimation" },
        ],
      },
      {
        text: "メッセージングとRPC",
        items: [
          { text: "メッセージキュー", link: "/parts/message-queue" },
          { text: "Pub/Sub", link: "/parts/pubsub" },
          { text: "RPC", link: "/parts/rpc" },
          { text: "イベントソーシング", link: "/parts/event-sourcing" },
          { text: "CQRS", link: "/parts/cqrs" },
        ],
      },
      {
        text: "画面が出るまで / フロント",
        items: [
          { text: "仮想DOM", link: "/parts/vdom" },
          { text: "リアクティビティ(signal)", link: "/parts/reactivity" },
          { text: "状態管理(store)", link: "/parts/store" },
          { text: "バンドラ(依存解決)", link: "/parts/bundler" },
          { text: "mini-next(SSR/ルーティング)", link: "/parts/mini-next" },
          { text: "browser(レンダリング)", link: "/parts/browser" },
        ],
      },
      {
        text: "計算機の土台",
        items: [
          { text: "小さな言語", link: "/parts/lang" },
          { text: "型推論(Hindley–Milner)", link: "/parts/type-inference" },
          { text: "2の補数とバイト順", link: "/parts/numbers" },
          { text: "メモリアロケータ", link: "/parts/allocator" },
          { text: "仮想メモリ", link: "/parts/virtual-memory" },
          { text: "正規表現(NFA/DFA)", link: "/parts/regex" },
          { text: "コンテナ", link: "/parts/container" },
          { text: "CPU スロットリング", link: "/parts/cpu-throttling" },
          { text: "OOM killer", link: "/parts/oom" },
          { text: "OS/スケジューラ", link: "/parts/os" },
        ],
      },
      {
        text: "ランタイム内部",
        items: [
          { text: "ガベージコレクタ", link: "/parts/gc" },
          { text: "イベントループ", link: "/parts/event-loop" },
          { text: "バイトコードVM", link: "/parts/bytecode" },
          { text: "スケジューラ(M:N)", link: "/parts/scheduler" },
          { text: "WebAssembly", link: "/parts/wasm" },
        ],
      },
      {
        text: "Kubernetesのなかみ",
        items: [
          { text: "調整ループ(reconciliation)", link: "/parts/reconcile" },
          { text: "スケジューラ(Podの配置)", link: "/parts/pod-scheduler" },
          { text: "水平オートスケール(HPA)", link: "/parts/autoscaler" },
          { text: "カスタム指標とKEDA", link: "/parts/custom-metrics" },
          { text: "Podの終了(graceful shutdown)", link: "/parts/pod-lifecycle" },
          { text: "init containerとsidecar", link: "/parts/init-container" },
          { text: "ヘルスチェック(probe)", link: "/parts/probe" },
          { text: "ローリング更新", link: "/parts/rollout" },
          { text: "Cluster Autoscaler", link: "/parts/cluster-autoscaler" },
          { text: "topology spread", link: "/parts/topology" },
          { text: "Serviceとkube-proxy", link: "/parts/service" },
          { text: "PodDisruptionBudget", link: "/parts/pdb" },
          { text: "PriorityClassとpreemption", link: "/parts/preemption" },
          { text: "StatefulSetとPVC", link: "/parts/statefulset" },
          { text: "CSIとボリューム", link: "/parts/csi" },
          { text: "JobとCronJob", link: "/parts/job" },
          { text: "DaemonSet", link: "/parts/daemonset" },
          { text: "ConfigMapとSecret", link: "/parts/config" },
          { text: "Ingress", link: "/parts/ingress" },
          { text: "Gateway API", link: "/parts/gateway-api" },
          { text: "NetworkPolicy", link: "/parts/network-policy" },
          { text: "RBAC", link: "/parts/rbac" },
          { text: "admission webhook", link: "/parts/admission" },
          { text: "SecurityContextとPSS", link: "/parts/pod-security" },
          { text: "ResourceQuotaとLimitRange", link: "/parts/quota" },
          { text: "APIサーバとinformer", link: "/parts/apiserver" },
          { text: "kubeletとCRI", link: "/parts/kubelet" },
          { text: "etcdの履歴と容量", link: "/parts/etcd-ops" },
          { text: "leader election", link: "/parts/leader-election" },
          { text: "Operatorパターン", link: "/parts/operator" },
        ],
      },
      {
        text: "暗号と認証",
        items: [
          { text: "ハッシュとHMAC", link: "/parts/hashing" },
          { text: "対称暗号とモード", link: "/parts/symmetric-cipher" },
          { text: "鍵交換(Diffie–Hellman)", link: "/parts/key-exchange" },
          { text: "暗号(RSA)", link: "/parts/crypto" },
          { text: "TLSハンドシェイク", link: "/parts/tls-handshake" },
          { text: "認証と認可", link: "/parts/auth" },
          { text: "OAuthと認可フロー", link: "/parts/oauth" },
        ],
      },
      {
        text: "ブロックチェーンのなかみ",
        items: [
          { text: "ブロックチェーン(鎖 + PoW)", link: "/parts/blockchain" },
          { text: "UTXO モデル", link: "/parts/utxo" },
          { text: "アカウント & EVM", link: "/parts/evm" },
          { text: "Layer2 / Rollup", link: "/parts/rollup" },
          { text: "Lightning / 決済チャネル", link: "/parts/lightning" },
          { text: "Substrate / ランタイム", link: "/parts/substrate" },
        ],
      },
      {
        text: "LLMのなかみ",
        items: [
          { text: "BPEトークナイザ", link: "/parts/bpe" },
          { text: "LLM Sampling", link: "/parts/llm-sampling" },
          { text: "行列演算", link: "/parts/tensor" },
          { text: "Attention", link: "/parts/attention" },
          { text: "mini-GPT", link: "/parts/mini-gpt" },
          {
            text: "Transformerの部品",
            items: [
              { text: "Transformer全体像", link: "/parts/transformer" },
              { text: "位置エンコーディングとRoPE", link: "/parts/rope" },
              { text: "attention変種(MQA/GQA)", link: "/parts/attention-variants" },
              { text: "RMSNormとSwiGLU", link: "/parts/rmsnorm-swiglu" },
              { text: "MoE", link: "/parts/moe" },
            ],
          },
          {
            text: "モデルを支える部品",
            items: [
              { text: "推論高速化", link: "/parts/inference" },
              { text: "学習パイプライン", link: "/parts/llm-training" },
              { text: "量子化", link: "/parts/quantization" },
              { text: "誤差を配る量子化(GPTQ)", link: "/parts/gptq" },
              { text: "枝刈り", link: "/parts/pruning" },
              { text: "LoRA", link: "/parts/lora" },
              { text: "埋め込みとベクトル検索", link: "/parts/embedding-search" },
              { text: "マルチモーダル入口(パッチ化)", link: "/parts/patchify" },
              { text: "エージェントの枠組み", link: "/parts/agent-harness" },
            ],
          },
          {
            text: "モデルの系譜",
            items: [
              { text: "GPT系譜", link: "/parts/gpt-lineage" },
              { text: "推論モデル(o1/R1)", link: "/parts/reasoning-models" },
              { text: "Claude(Constitutional AI)", link: "/parts/claude-lineage" },
              { text: "Gemini(マルチモーダル)", link: "/parts/gemini-lineage" },
              { text: "オープンモデル", link: "/parts/open-models" },
              { text: "Mamba / SSM", link: "/parts/ssm" },
            ],
          },
          { text: "LLM全体マップ", link: "/parts/llm-architecture" },
        ],
      },
    ],
    socialLinks: [{ icon: "github", link: "https://github.com/esh2n/sharin" }],
    outline: { label: "この章の目次", level: [2, 3] },
    docFooter: { prev: "前の章", next: "次の章" },
    lastUpdated: { text: "最終更新" },
  },
});
